variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US"
  LIB_NAME: "terminal-service-provider"
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.console=plain -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository"
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: "2"
  SECRET_DETECTION_EXCLUDED_PATHS: ".gradle,gradle,.m2"

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Secret-Detection.gitlab-ci.yml

default:
  image: gradle:jdk17
  tags:
    - docker

cache:
  paths:
    - ".gradle/wrapper"
    - ".gradle/caches"
    - ".m2/repository"

workflow:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "develop" || $CI_COMMIT_REF_NAME =~ /^release.*$/ || $CI_COMMIT_REF_NAME =~ /^feature.*$/'

assemble:
  script: |
    ./gradlew --continue clean assemble test build
  artifacts:
    when: always
    paths:
      - "build/libs"
    reports:
      junit: "build/test-results/test/**/TEST-*.xml"

spotbugs-sast:
  needs:
    - job: assemble
      artifacts: true
  variables:
    MAVEN_REPO_PATH: "./.m2/repository"
    COMPILE: "false"
    SAST_EXCLUDED_PATHS: ".gradle, test"
  artifacts:
    reports:
      sast: "gl-sast-report.json"
