spring:
  application:
    name: ${SPRING_APPLICATION_NAME:wallet-relying-party}
  config:
    import: "${SPRING_CONFIG_IMPORT:optional:configserver:}"
  cloud:
    config:
      enabled: ${SPRING_CLOUD_CONFIG_ENABLED:false}
      uri: ${SPRING_CLOUD_CONFIG_URI:}
  threads:
    virtual:
      enabled: true
app:
  public-context: http://localhost:8080
  wrp:
    alias: alias
    key-store: classpath:demo-wrp/wrp.p12
    password: password
    rc:
      - label: Entwicklungsübersicht
        jws: classpath:demo-wrp/wrprc-entwicklung.jws
      - label: Altersprüfung 18+
        jws: classpath:demo-wrp/wrprc-alterspruefung.jws
      - label: Identitätsprofil
        jws: classpath:demo-wrp/wrprc-identitaetsprofil.jws
      - label: Adressübersicht
        jws: classpath:demo-wrp/wrprc-adressuebersicht.jws