spring:
  application:
    name: ${SPRING_APPLICATION_NAME:wallet-relying-party}
  config:
    import: "${SPRING_CONFIG_IMPORT:optional:configserver:}"
  cloud:
    config:
      enabled: ${SPRING_CLOUD_CONFIG_ENABLED:false}
      uri: ${SPRING_CLOUD_CONFIG_URI:}
  threads:
    virtual:
      enabled: true
app:
  public-context: http://localhost:8080
