[versions]
qrcode = "4.5.0"
vck = "7.0.0-RC1"

spring-boot = "4.1.0"
spring-cloud = "2025.1.2"
spring-admin-starter-client = "4.1.1"

kotlin = "2.3.20"

[libraries]
spring-boot-admin-starter-client = { module = "de.codecentric:spring-boot-admin-starter-client", version.ref = "spring-admin-starter-client" }
qrcode-kotlin = { module = "io.github.g0dkar:qrcode-kotlin", version.ref = "qrcode" }
wallet-vck = { module = "at.asitplus.wallet:vck", version.ref = "vck" }
wallet-vck-openid = { module = "at.asitplus.wallet:vck-openid", version.ref = "vck" }
wallet-vck-openid-ktor = { module = "at.asitplus.wallet:vck-openid-ktor", version.ref = "vck" }
