package at.asit.apps.terminal_sp.prototype.server

import at.asit.apps.terminal_sp.prototype.server.util.AntilogSlf4jAdapter
import at.asitplus.wallet.lib.Initializer.initOpenIdModule
import at.asitplus.wallet.lib.agent.Verifier
import at.asitplus.wallet.lib.jws.SdJwtSigned
import io.github.aakira.napier.Napier
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test

class PotentialLookup {

    companion object {
        @BeforeAll
        @JvmStatic
        fun beforeAll() {
            initOpenIdModule()
            Napier.takeLogarithm()
            Napier.base(AntilogSlf4jAdapter)
        }
    }

    @Disabled
    @Test
    fun `potential sd jwt from IT`() = runTest {
        val input = """
            eyJraWQiOiJvTHZHOHFGeGJZQ2RZRXBGNVdEeEJVYzM1THI1YTgwZ2FtbjZPeU5pSFRjIiwidHlwIjoidmMrc2Qtand0IiwiYWxnIjoiRVMyNTYifQ.eyJzdWIiOiJiTFVoWF9RRzFsNG1TUlpVdWw0a0Y4Z0RUWTRidDZjQ2ZjeEQ4U3JmTmgwIiwiX3NkIjpbIjFNNllBQzBLZVhyUkFVaGtiQXpkbERPWGp0Q2tENXktSWZNeWhsMzlMM2MiLCI4bmI3dVNVXzNtOVBsYnBTSG9TclRMNWItZF8wNzNIXzdsSWkzaVFUTkhzIiwiOTU3OGgtX0hleUJkdnZHbWwtbDZiUG5Ia1p3Umt5U3Jhemo3Q0VPZ1RRSSIsIlExUVNrNVpvVWViS183VTA2SDlUV3NLejE2RHFhbWYtaU9FWDY2WEt4T1kiLCJjNDJibFJ2WEVMQ0s3TnY2eFhvRlhPQWI0dU43ckVWaU1jNWNSQVJsMzRVIiwiZmotalhGcGgzeXJVWE5MVDNJRFVwZjl0cGJUVDIzQ3pFYXFPNHhVR2xNMCIsImdfYXM4ZlYyLWZHZ0Uwcm9HZmxsRF9nQjExRjVvV25OUjBxejV1VW84QTAiLCJqRWpLV3hEckFxaEhNY3l3ckNRZHNhcnhLT19IWF96d2lyTm01UlFLcHNrIl0sInZjdCNpbnRlZ3JpdHkiOiIyNDIzMDJkOTdkMzhkYTI3MTRhMjU3ZjJhMjUzYmYyZmEzMGFhZTVjMTA5ZmU5NTgxYmZjZGEzYjFkNzk3Yzk3IiwiX3NkX2FsZyI6InNoYS0yNTYiLCJ2Y3QiOiJ1cm46ZXUuZXVyb3BhLmVjLmV1ZGk6cGlkOjEiLCJpc3MiOiJodHRwczovL2FwaS5wb3RlbnRpYWwtd2FsbGV0LWl0LXBpZC1wcm92aWRlci5pdCIsImNuZiI6eyJqd2siOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsImtpZCI6IkIydkg1MTF2aUF6SlBlY0g4NTlXb1BfS2UtUGdlWVUyMWo4aTg2dWdlaDQiLCJ4IjoiN2RHTWRZSzF5SEd0LVhnVnB4aUJDQ21uNG5PSlh0V3BaeDRLeXlCQzdGOCIsInkiOiI1bUxPV0FmMlkxbVZVTlNLN2YxelVHY204REk3RXJ6UnVMTWNWOUJqLXg0In19LCJleHAiOjE3NzgwNjkwOTksImlhdCI6MTc0NjUzMzA5OSwidmVyaWZpY2F0aW9uIjp7ImV2aWRlbmNlIjp7Im1ldGhvZCI6ImNpZSJ9LCJ0cnVzdF9mcmFtZXdvcmsiOiJlaWRhcyIsImFzc3VyYW5jZV9sZXZlbCI6ImhpZ2gifSwic3RhdHVzIjp7InN0YXR1c19hc3NlcnRpb24iOnsiY3JlZGVudGlhbF9oYXNoX2FsZyI6InNoYS0yNTYifX19.CukRx1fn_rvCRdpSrBmRs60uC5IQG6dVnVQ17TdzscDlfr-8QscVmX97P7_P9xfJXYcSHU3o0fHM-h9M7RyXSA~
        """.trimIndent()

        val result = VerifierProfiles("http://localhost/").potentialValidator().verifySdJwt(SdJwtSigned.parse(input)!!, null).also { println(it) }

        result as Verifier.VerifyCredentialResult.SuccessSdJwt
        Assertions.assertNotNull(result.sdJwtSigned)
    }

    @Disabled
    @Test
    fun `potential sd jwt from FI`() = runTest {
        val vpToken = """
            eyJhbGciOiJFUzI1NiIsInR5cCI6InZjK3NkLWp3dCIsIng1YyI6WyJNSUlDNWpDQ0FtMmdBd0lCQWdJVU9LbkVIaFh3cmN3ZDY0cHV6WnlmQkprY3VJY3dDZ1lJS29aSXpqMEVBd0l3Z2FneE9EQTJCZ05WQkFNTUwwUldWaUJFYVdkcExVbEVJRTF2WTJzZ1FYUjBjbWxpZFhSbElGTmxZV3hwYm1jZ1EyVnlkR2xtYVdOaGRHVnpNU1l3SkFZRFZRUUtEQjFFYVdkcExTQnFZU0IydzZSbGMzVER0blJwWlhSdmRtbHlZWE4wYnpFUk1BOEdBMVVFQnd3SVNHVnNjMmx1YTJreEN6QUpCZ05WQkFZVEFrWkpNUkF3RGdZRFZRUUlEQWRHYVc1c1lXNWtNUkl3RUFZRFZRUUZFd2t3TWpRMU5ETTNMVEl3SGhjTk1qUXdOVEUyTURnME56STNXaGNOTWpVd05URTJNRGcwTnpJM1dqQ0JwekUzTURVR0ExVUVBd3d1UkZaV0lFUnBaMmt0U1VRZ1RXOWpheUJCZEhSeWFXSjFkR1VnVTJWaGJHbHVaeUJEWlhKMGFXWnBZMkYwWlRFbU1DUUdBMVVFQ2d3ZFJHbG5hUzBnYW1FZ2RzT2taWE4wdzdaMGFXVjBiM1pwY21GemRHOHhFVEFQQmdOVkJBY01DRWhsYkhOcGJtdHBNUXN3Q1FZRFZRUUdFd0pHU1RFUU1BNEdBMVVFQ0F3SFJtbHViR0Z1WkRFU01CQUdBMVVFQlJNSk1ESTBOVFF6TnkweU1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRVdTaWluVE5RWXFZZWwvS0tnYjRzVXZJQTVCZ0Zmdyt1ckpaRW1RaEJablZweitTZ1hoa2hrNk9NZ0Z6Y0hBUWZDYzBIcDhSRWc2NkJIZnM2VUtKbzJxTjBNSEl3RHdZRFZSMFRBUUgvQkFVd0F3SUJBREFPQmdOVkhROEJBZjhFQkFNQ0I0QXdGUVlEVlIwbEFRSC9CQXN3Q1FZSEtJR01YUVVCQWpBWkJnTlZIUklFRWpBUWhnNW9kSFJ3Y3pvdkwyUjJkaTVtYVRBZEJnTlZIUkVFRmpBVWdoSnhZUzVwWkM1amJHOTFaQzVrZG5ZdVpta3dDZ1lJS29aSXpqMEVBd0lEWndBd1pBSXdCemx5Q3RVL090aVpYOU94Tit1YWlFbUgybTgrY21sRTA0dzgyem9JRE0wbXRuK01TSGhIV0w2TEZybXpOMmFYQWpCczNIY1ZwQncySnNpTmJ3TFY5RXUzTHNha2hBQlA0SnlpejlydngyZXJMQUNuRUpPVzBCNGsyWkpvR0hmWnBWUT0iXX0.eyJfc2QiOlsiNy1GQjZxeWZPV2d5NS1ZcHZpYnRvRWdhUWtoOF9YV19fUHBqcVRtN2xLTSIsIklHMWRDbkpiMXJVeWJQeklONkotQkNDLWdfUF9PT3pxR3JvblE1Y0ltSFkiLCJDVllxUXgweU5QZ0ptMXAtdTNkR3BZQnFhSE82dkZGWTA0WVo1Rk1tVXNvIiwiLW8tOExfY0NqRmpjX2YteU9JTTJuMnB1STlmQmpIbHlFclp2SHZhVDRidyIsImc3SUVNSGlhNFdURUxsQmxSQ3JlOFFyWjBrYTJ1MFo5SjFNbzlJM3dUV28iLCJmeXZhdFBHa3BhdW15TVZ2Wm9vRFR3V2JDRnYwdFB0VFNIZWVfeXNsVHZFIiwiYVBXTnJzeE8wR25WVGI5RGhMSHdmOUJ6MG9CWEVldlIwS09fN3JFSmk1RSIsIlVlM3NSR1h6NjNoc2wzNnl6VzhGdXdnc1lKdEJvTDJ6MVlyQnhPczlwZkEiLCJSOEZPZWUzRUhCVGNNTjlhZWhzVndrZWdGVzZXUUJKWGVndW10V0tGM3NrIiwicFVuNFNiUEJXajAxWXVkbWV1WThZN2pfeEZyRno0T2pLRWtqVXdlT0huSSIsIlg0VGstS0FiMHljU0QzMF92YlVodTMzY1pnNHNic1pweXdDeGNLNHBXcnMiLCJWbEw1NnlGYkFNUFI1bVhKTXNmNmxCMTZhUURJVDZ4eElENThad0k5cV9FIl0sIm5iZiI6MTczNzk3NzQ5NCwiX3NkX2FsZyI6InNoYS0yNTYiLCJ2Y3QiOiJ1cm46ZXUuZXVyb3BhLmVjLmV1ZGk6cGlkOjEiLCJpc3MiOiJodHRwczovL3FhLmlkLmNsb3VkLmR2di5maS9waWQtcHJvdmlkZXIvcGlkLzEuMCIsImNuZiI6eyJqd2siOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJHcFN6YW9rdUl2T0xQa2ZKSUlwajJxaDItVE5JS2hzaTk5RnRoMF9hcnJvIiwieSI6IlJZOGQ3ckZVV21ibmJldmxvY0tBYTNuRFozcGJ5cWhBVUtVWEZNVTcwRnMifX0sImV4cCI6MTc0NTc1MzQ5NCwiaWF0IjoxNzM3OTc3NDk0LCJzdGF0dXMiOnsic3RhdHVzX2xpc3QiOnsidXJpIjoiaHR0cHM6Ly9xYS5pZC5jbG91ZC5kdnYuZmkvc3RhdHVzLWxpc3QtdG9rZW4vODExYjhmZDctMzE4YS00YzUxLTgyMjQtNjhmZTE2ZDY5MzRiIiwiaWR4IjozODU5MzZ9fX0.K5g7oOTcZngpFNTYe7Hg4nvEn0TTQPh40fe4fBcjNQ1GpqoqBHmo8Xai37NnxK-tdNNxbHEI99UUcOlRXXUP3Q~WyJESXVIanc5d0MxSzZoQmd3LWphUEx3IiwiZmFtaWx5X25hbWUiLCJMYW5kbWFuc3NvbiJd~WyJlMkxWaWxLa0FxUlV4QmJQUTRWN0JnIiwiZ2l2ZW5fbmFtZSIsIlJvbGYiXQ~WyI0V1IxcVpOWGlReFE0YzBrQ1loZVdnIiwiYmlydGhfZGF0ZSIsIjE5OTctMDctMTEiXQ~WyJOM0U1TzNRajNwWHdvZDVlWVdkS2dnIiwiYWdlX292ZXJfMTgiLHRydWVd~eyJ0eXAiOiJrYitqd3QiLCJhbGciOiJFUzI1NiJ9.eyJzZF9oYXNoIjoibUcwVVNKNW9ISjhfTU4yZXAzUHZLaUxtb1lZaXVlVXlmVzVGTG9lX2VTayIsImF1ZCI6IkFULUdWLUVHSVotQ1VTVE9NVkVSSUZJRVIiLCJuYmYiOjE3MzgwNTk4ODIsImV4cCI6MTczODA2MDE4MiwiaWF0IjoxNzM4MDU5ODgyLCJub25jZSI6ImY3ZTVmODY4LWUxNTAtNDNlOC1hMTZkLWM5ZDBiMTM0NjQxMyJ9.QSYSaBvN-VfsJQ9v9tOZ07nwE0zalbF6bGbodJzWjT8HJzgRVP37iV8SpqYUUXqpXmxtwSY0tuyLvtSIFGGcYg
        """.trimIndent()

        val result = VerifierProfiles("http://localhost").getVerifierByName("Potentialv1")!!.verifier
            .verifyPresentationSdJwt(SdJwtSigned.parse(vpToken)!!, "f7e5f868-e150-43e8-a16d-c9d0b1346413").also { println(it) }

        result as Verifier.VerifyPresentationResult.SuccessSdJwt
        Assertions.assertNotNull(result.sdJwtSigned)
    }
}