package at.asit.apps.terminal_sp.prototype.server

import at.asit.apps.terminal_sp.prototype.server.util.AntilogSlf4jAdapter
import at.asitplus.wallet.lib.Initializer.initOpenIdModule
import at.asitplus.wallet.lib.agent.Verifier
import at.asitplus.wallet.lib.jws.SdJwtSigned
import at.asitplus.wallet.lib.oidc.OidcSiopVerifier
import io.github.aakira.napier.Napier
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.Test

class PotentialLookup {

    companion object {
        @BeforeAll
        @JvmStatic
        fun beforeAll() {
            initOpenIdModule()
            Napier.takeLogarithm()
            Napier.base(AntilogSlf4jAdapter())
        }
    }

    @Test
    fun `potential sd jwt`() = runTest {
        val input = """
            eyJraWQiOiJlTk4tZzVpNkNuTEtjbHRRQnA2YWJiaW9HTWJ6TTZtdVczdnV4dzZ1aDg4IiwidHlwIjoidmMrc2Qtand0IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJuR1RmZXhuSTNDZ1E0TWZDSDN3ZlRNSVFyVjE3WWc1YkN3bkl2Vk1RbVFzIiwiX3NkIjpbIkdTUFpBTlNLaUNfejNVTkpLXzdkY2FZQWg4SmVOWnJtalpQOG0yam81QzQiLCJHWXNSMEloSzNocVN5YkNjTXN3ZDZ6RFF0cjk0YmxFbUp5NU5WSHZmRkZFIiwiUThQZnBwaWhfWjczeFJXdDU1aUpzbTN0cnRZdVdvRkN2YW1kbUZqYWNndyIsIlV1QU9hZjBXY1lHRWFYQXI4N3lwZEdxUEIydmV0NjNCV3ZEQ21Yb3hWazAiLCJfSU4wc3hjUjdkSVRPQ0FCZzQ2TFBvQWplUDV1a1hWSHFhZk9KMWNkbFBnIiwiX0o5UU0yQXVGWHFDNEEtMUV4dnZOZVpOZFJVejc3bDZGUWhCc1ZGa2pjQSJdLCJ2Y3QjaW50ZWdyaXR5IjoiMjQyMzAyZDk3ZDM4ZGEyNzE0YTI1N2YyYTI1M2JmMmZhMzBhYWU1YzEwOWZlOTU4MWJmY2RhM2IxZDc5N2M5NyIsIl9zZF9hbGciOiJzaGEtMjU2IiwidmN0IjoidXJuOmV1LmV1cm9wYS5lYy5ldWRpOnBpZDoxIiwiaXNzIjoiaHR0cHM6Ly9hcGkucG90ZW50aWFsLXdhbGxldC1pdC1waWQtcHJvdmlkZXIuaXQiLCJjbmYiOnsiandrIjp7Imt0eSI6IkVDIiwiY3J2IjoiUC0yNTYiLCJraWQiOiJ1N2dDeWxodlh0NEZVQnhhY080LVg3QTM3NVE2ZThONG9ZeGdzNl9lb0FrIiwieCI6ImR0NXNmTnNEYXVtbHkyRWhVNW9KTHJQT1VoeWZUdm0xeFMwVjg0elhUS28iLCJ5IjoiUjBYOEpMVlRxYko3aW85NUpoam9nVEk1SGhRRFZIYXB4Z2RKQ1FLR2tfMCJ9fSwiZXhwIjoxNzY4OTI0NjMzLCJpYXQiOjE3MzczODg2MzMsInZlcmlmaWNhdGlvbiI6eyJldmlkZW5jZSI6eyJtZXRob2QiOiJjaWUifSwidHJ1c3RfZnJhbWV3b3JrIjoiZWlkYXMiLCJhc3N1cmFuY2VfbGV2ZWwiOiJoaWdoIn0sInN0YXR1cyI6eyJzdGF0dXNfYXNzZXJ0aW9uIjp7ImNyZWRlbnRpYWxfaGFzaF9hbGciOiJzaGEtMjU2In19fQ.PEPYBG0XDFYeU9NaOaMcFS6jcMcMGCEAr44s2Pa7d4OD3_yYpK_A-vVuh_5ILnMaEdL6MmYNFPlMB1RdA3cid0z6hBoOxei1yl-SHXI6PtaAmF6EljNTsgf1FoqbQ1CAOEYtTvr-_EHUE8XH8hUEEKsPMNnVgCZ48vidjJeJj6cuMCaY-_of7BNKq4-JjIC0j5mtKrikMKEFStH2RGXs8Qrj69sWJvFMiSPvDUPR9XCGofda0axSXo6El1B7ab-eawA6csj0GT0bczAXSAT5q1Mu02rJ8H1I6rsm9OU_uZmmyHO3IXerlhW56ZDu70pSm8PKDvYwzqhC6xV7X-IqLg~WyJCNFBQWXZmMTVnc0EtenRySmw0eFR3IiwiZ2l2ZW5fbmFtZSIsIk1hcmlvIl0~WyJ0WjExV0hnZlpmeUl5VGl3U3NmQklnIiwiZmFtaWx5X25hbWUiLCJSb3NzaSJd~WyIzRlg2NXRndDE1cUlBLThUa0sxRUh3IiwidW5pcXVlX2lkIiwiaWRBTlBSIl0~WyItX19hUGVLYUNtYmRDcVpXbDlFWG5nIiwiYmlydGhfZGF0ZSIsIjE5ODAtMTAtMDEiXQ~WyJvenp1RlVRemdVVzQ2a0dCeHZPaFBBIiwidGF4X2lkX2NvZGUiLCJUSU5JVC1SU1NNUkE4MEExMEg1MDFBIl0~WyI1WU52VTNnT1BOam8yZmNLdGFFSXJBIiwiaWF0IiwxNzM3Mzg4NjMzXQ~eyJ0eXAiOiJrYitqd3QiLCJhbGciOiJFUzI1NiJ9.eyJzZF9oYXNoIjoiMmU1OGRiZWExMmY0MzAyZmRlN2I3N2I4ZmY3OWYyMTYzYjJjYzdjM2NjY2QyMDUyMDdmZWE5MjFjZWQ3ZDc0NCIsIm5vbmNlIjoiNTJlNzU4ZTUtNTA4Ny00M2NkLTljMTktOTcxYWE3MmMwZjQ1IiwiYXVkIjoiaHR0cHM6Ly9hcHBzLmVnaXouZ3YuYXQvY3VzdG9tdmVyaWZpZXIvdHJhbnNhY3Rpb24vcmVzdWx0LzA1NGVkZmZkLTE3ZDctNDlhNi1hOTY5LWU3Mjc1YTM4YTFjNyIsImlhdCI6MTczNzQ3MzkzMH0.e64A0BiR-0zTJ4KLaX0fC_0aTi4gVeKLBofNFDM9j386BVBDDJfcATmFevzmJntGNAAK85u4Hj3EggXoDHxOug
        """.trimIndent()

        val result = VerifierProfiles("foo").potentialValidator().verifySdJwt(SdJwtSigned.parse(input)!!, null).also { println(it) }

        result as Verifier.VerifyCredentialResult.SuccessSdJwt
        Assertions.assertNotNull(result.sdJwtSigned)
    }
}